baseURL = 'https://adventureswithsusieandtim.com/'
copyright = "{year}"
languageCode = 'en-us'
theme = 'lowkey'
title = 'Susie & Tim Get Married!'
enableRobotsTXT = true

# List Config
summaryLength= 2
paginate = 5

[markup.highlight]
      codeFences = false
      guessSyntax = false
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false
